version: '3.8'
services:
  backend:
    build:
      context: ./the-harry-list-backend
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: tst
    restart: unless-stopped