name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test-security-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run tests
        run: mvn test

      - name: Check for security vulnerabilities
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn org.owasp:dependency-check-maven:check
